AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  BaseAmi:
    Type: AWS::EC2::Image::Id
    Description: Base AMI to build intermediate images on top of.
    # TODO this is regional, hard coded us-east-1 for now. Perhaps an SSM
    # input parameter for this stack is best here?
    Default: ami-0742dbb6cdf78ac94

  SecretsBucket:
    Type: String
    Description: Optional – Buildkite elastic-ci stack secrets bucket.
    Default: ""

  BootstrapScriptUrl:
    Type: String
    Description: AMI customisation script, downloaded and executed as part of the image build.

  InstanceType:
    Type: String
    Description: Instance type for the Image Builder instances.

  ScheduleExpression:
    Type: String
    Description: "cron expression for when to run image builds, defaults to nightly at midnight."
    Default: "0 0 0 1/1 * ? *"

Conditions:
  HasSecrets:
    !Not [ !Equals [ !Ref SecretsBucket, "" ]]

Resources:
  # IAM role for the image builder instance
  InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/EC2InstanceProfileForImageBuilder
      Policies:
        - !If
            - HasSecrets
            - PolicyName: SecretsBucketAccess
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - s3:Get*
                      - s3:Get
                      - s3:List*
                    Resource:
                      - !Sub "arn:aws:s3:::${SecretsBucket}/*"
                      - !Sub "arn:aws:s3:::${SecretsBucket}"
            - !Ref AWS::NoValue
  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref InstanceRole

  # Component that optionally syncs the SecretsBucket, downloads and executes
  # the script, and cleans up the secrets bucket cache
  Component:
    Type: AWS::ImageBuilder::Component
    Properties:
      Name: !Sub "${AWS::StackName}-Bootstrap"
      Platform: Linux
      Version: '0.1.0'
      Description: Optionally fetch an S3 SecretsBucket, and execute a bootstrap script.
      Data: |
        name: BootstrapAmi
        description: Optionally fetch an S3 SecretsBucket, and execute a bootstrap script.
        schemaVersion: 1.0

        phases:
          - name: build
            steps:
              - name: FetchSecrets
                action: ExecuteBash
                inputs:
                  commands:
                    - echo fetching secrets
              - name: ExecuteBootstrap
                action: ExecuteBash
                inputs:
                  commands:
                    - echo executing bootstrap
              - name: RemoveSecrets
                action: ExecuteBash
                inputs:
                  commands:
                    - echo removing secrets

  # Recipe of the base image + component
  Recipe:
    Type: AWS::ImageBuilder::ImageRecipe
    Properties:
      Name: !Sub "${AWS::StackName}-Recipe"
      Components:
        - ComponentArn: !Ref Component
      ParentImage: !Ref BaseAMi
      Version: "0.1.0"

  # Publicly routable subnet (route table 0.0.0.0/0 -> igw) in a vpc
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
  Gateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
  GatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref Gateway
      VpcId: !Ref Vpc
  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, { Fn::GetAZs: !Ref AWS::Region } ]
      CidrBlock: 10.0.0.0/24
      VpcId: !Ref Vpc
      Tags:
        - Key: Name
          Value: !Ref AWS::StackName
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable bootstrap instance egress.
      VpcId: !Ref Vpc
      SecurityGroupEgress:
        - Description: Egress to any IPv4
          IpProtocol: -1
          CidrIp: 0.0.0.0/0
        - Description: Egress to any IPv6
          IpProtocol: -1
          CidrIpv6: ::/0
      Tags:
      - Key: Name
        Value: !Ref AWS::StackName
  Infrastructure:
    Type: AWS::ImageBuilder::InfrastructureConfiguration
    Properties:
      Name: !Sub "${AWS::StackName}-Infrastructure"
      InstanceProfileName: !Ref InstanceProfile
      InstanceTypes:
        - !Ref InstanceType
      SubnetId: !Ref PublicSubnet
      SecurityGroupIds:
        - !GetAtt SecurityGroup.GroupId
      TerminateInstanceOnFailure: true
      SnsTopicArn: !Ref PipelineTopic

  # Copy to this region only
  Distribution:
    Type: AWS::ImageBuilder::DistributionConfiguration
    Properties:
      Name: !Sub "${AWS::StackName}-Distribution"
      Distributions:
        - Region: !Ref AWS::Region

  # Composition of the above elements
  Pipeline:
    Type: AWS::ImageBuilder::ImagePipeline
    Properties:
      Name: !Sub "${AWS::StackName}-Pipeline"
      DistributionConfigurationArn: !Ref Distribution
      ImageRecipeArn: !Ref Recipe
      InfrastructureConfigurationArn: !Ref Infrastructure
      Schedule:
        PipelineExecutionStartCondition: EXPRESSION_MATCH_ONLY
        ScheduleExpression: !Ref ScheduleExpression

  # Topic for the pipeline to notify
  PipelineTopic: {}
  # Lambda that receives notifications from the pipeline sns topic
  BuiltLambda: {}
  # Output parameter that is updated for builds from the pipeline
  OutputParameter: {}
  # Output topic that is notified for each modification to the output parameter
  OutputTopic: {}

Outputs: {}
